Four/Four/urls.py
from django.contrib import admin
from django.urls import path, include
from basic_app import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('basic_app/', include('basic_app.urls')),
    path("",views.index,name='index'),
    path('logout/',views.user_logout,name='logout'),
    path('special/',views.special,name='special')
]

Four/basic_app/urls.py
from django.urls import path
from . import views
#template tagging
app_name = 'basic_app'

urlpatterns=[
path("register",views.register, name="register"),
path('user_login/',views.user_login,name='user_login'),
path('',views.index,name='index'),
#path("other",views.other, name="other")



]

Four/basic_app/models.py
from django.db import models
from django.contrib.auth.models import User

class UserProfileInfo(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE,
        primary_key=True)
# Create your models here.
    portfolio_site = models.URLField(blank=True)
    profile_pic=models.ImageField(upload_to='profile_pic', blank=True)

    def __str__(self):
        return self.user.username

Four/basic_app/forms.py
from django import forms
from django.contrib.auth.models import User
from basic_app.models import UserProfileInfo


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())
    class Meta():
        model=User
        fields = ('username','email','password')

class UserProfileInfoForm(forms.ModelForm):
    class Meta():
        model= UserProfileInfo
        fields =('portfolio_site','profile_pic')

Four/basic_app/views.py
from django.shortcuts import render
from .forms import UserProfileInfoForm, UserForm
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect, HttpResponse
from django.contrib.auth import authenticate, login, logout

# Create your views here.
def index(request):
    return render(request, 'basic_app/index.html')

def register(request):
    registred=False
    if request.method =="POST":
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileInfoForm(data=request.POST)
        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()

            profile=profile_form.save(commit=False)
            profile.User=user.username
            print("one")
            if 'profile_pic' in request.FILES:
                profile.profile_pic=request.FILES['profile_pic']
            profile.save()
            registred= True
            print("two")
        else:
            print(user_form.errors,profile_form.errors)
    else:
        user_form= UserForm()
        profile_form = UserProfileInfoForm


    return render(request, 'basic_app/registration.html',{'user_form':user_form,'profile_form':profile_form,'registred':registred })

def user_login(request):
    if request.method=="POST":
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username,password=password)
        if  user:
            if user.is_active:
                login(request,user)
                return HttpResponseRedirect(reverse('index'))
            else:
                return HttpResponse("ACCOUNT NOT ACTIVE")
        else:
            print("tried login and failed")
            return HttpResponse("invalid login datails")
    else:
        return render(request, 'basic_app/login.html',{})

@login_required
def special(request):
    return HttpResponse("you are log with special")


@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))





def another(request):
    return render(request, 'basic_app/another.html')

Four/templates/basic_app/another.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <h1>Welcome another</h1>
    <a href="{% url "basic_app:other" %}">The other page</a>
  </body>
</html>

Four/templates/basic_app/base.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title></title>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">  </head>

  <body>
    <nav class="navbar navbar-default navbar-static-top">
      <div class="container">
        <ul class="nav navbar-nav">
          <div class="nav-item"> <li> <a class="navbar-brand" href="{% url "index" %}">Django</a></li></div>
          <li> <a class="navbar-link" href="{% url "admin:index"%}">Admin</a></li>
          <li> <a class="navbar-link" href="{% url "basic_app:register"%}">Register</a></li>

          {%if user.is_authenticated %}
          <li> <a class="navbar-link" href="{% url "logout"%}">Logout</a></li>
          {%else%}
          <li> <a class="navbar-link" href="{% url "basic_app:user_login"%}">Login</a></li>
          {%endif%}
        </ul>
      </div>
    </nav>

    <div class="container">

      {% block body_block %}

     {% endblock %}
    </div>

  </body>
</html>

Four/templates/basic_app/index.html
{% extends "basic_app/base.html"%}
{% block body_block %}
<h1>Welcome to index</h1>

      <a href="{% url "basic_app:index" %}">The another page</a>
{% endblock %}

Four/templates/basic_app/login.html
{%extends 'basic_app/base.html'%}

{%block body_block%}
<h1>Please Login</h1>
<form action="{% url 'basic_app:user_login'%}" method="post">
  {%csrf_token%}
  <label for="username">Username:</label>
  <input type="text" name="username" placeholder="Enter Username">
  <label for="password">Password:</label>
  <input type="password" name="password">

  <input type="submit" name="" value="Login">

</form>
{%endblock%}

Four/templates/basic_app/other.html
<!DOCTYPE html>
{% extends "basic_app/base.html"%}
{%block body_block%}
    <h2>Welcome other</h2>
      <a href="{% url "index" %}">go to index</a>
      <h3>Example inderitance</h3>
      {% endblock %}

Four/templates/basic_app/registration.html
{% extends 'basic_app/base.html' %}
{% load staticfiles%}

{%block body_block %}

{% if registred %}
{{registred}}
<h1>Thank you for registeriing !</h1>
{% else %}
<h1>Register here</h1>
{% if registred %}
  {% endif %}
<form enctype="multipart/form-data" method="POST">
  {% csrf_token%}
  {{user_form.as_p}}
  {{profile_form.as_p}}
  <input type="submit" name="" value="Register">

  {% endif %}
{% endblock%}
</form>